"""empty message

Revision ID: bc98ecd63310
Revises: edbf0c46732e
Create Date: 2023-05-01 17:28:10.473347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc98ecd63310'
down_revision = 'edbf0c46732e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint(None, ['pay'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pay')

    # ### end Alembic commands ###
